name: fl_bar_chart_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.16.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true